# Generated by Django 5.1.1 on 2024-09-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rombooking_api', '0003_bookingrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='desired_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
