# Generated by Django 5.1.1 on 2024-09-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rombooking_api', '0005_brukerdetaljer'),
    ]

    operations = [
        migrations.AddField(
            model_name='brukerdetaljer',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
