# Generated by Django 5.1.1 on 2024-09-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rombooking_api', '0007_bookingrequest_desired_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='desired_building',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
