# Generated by Django 5.1.1 on 2024-09-30 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rombooking_api', '0008_bookingrequest_desired_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='desired_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
