# Generated by Django 5.1.1 on 2024-10-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rombooking_api', '0009_alter_bookingrequest_desired_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
