# Generated by Django 5.1.1 on 2024-10-01 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rombooking_api', '0010_bookingrequest_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='brukerdetaljer',
            name='profile_approved',
            field=models.BooleanField(default=False),
        ),
    ]
