# Generated by Django 5.1.1 on 2024-10-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rombooking_api', '0011_brukerdetaljer_profile_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='booking_hour',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
