# Generated by Django 5.1.2 on 2024-10-23 15:47

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rombooking_api', '0013_usercredentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brukerdetaljer',
            name='feide_password',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
