# Generated by Django 5.1.2 on 2024-12-25 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rombooking_api', '0017_alter_bookingrequest_desired_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='desired_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rombooking_api.room'),
        ),
    ]
