# Generated by Django 5.1.2 on 2024-12-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rombooking_api', '0018_alter_bookingrequest_desired_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='instant_booking',
            field=models.BooleanField(default=False),
        ),
    ]
