# Generated by Django 5.1.2 on 2024-12-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rombooking_api', '0019_bookingrequest_instant_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='booked_room',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
