# Generated by Django 5.1.2 on 2024-12-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rombooking_api', '0020_bookingrequest_booked_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingrequest',
            name='progress',
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='progress_delay',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
