# Generated by Django 5.1.2 on 2024-12-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rombooking_api', '0021_remove_bookingrequest_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brukerdetaljer',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
