# Generated by Django 5.1.2 on 2024-12-29 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rombooking_api', '0022_brukerdetaljer_last_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brukerdetaljer',
            name='last_activity',
        ),
    ]
