# Generated by Django 5.1.2 on 2024-12-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rombooking_api', '0024_remove_room_image_room_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image_url',
            field=models.URLField(default='https://eloquent-salmiakki-2cbe5c.netlify.app/room_dont_exist.png'),
        ),
    ]
